### ISSUE TITLE
Spec for ZenEx.Model.Ticket.Show does not include `nil` return type

### ISSUE THREAD

**Issue by davelively14** [otoyo/zendex#13]
Great library - enjoying it so far. 

I did find one tiny issue that's throwing me some Dialyzer warnings. The spec on [line 35](https://github.com/otoyo/zen_ex/blob/master/lib/zen_ex/core/models/ticket.ex#L35) for `ZenEx.Model.Ticket.Show` does not account for `nil`. I think that's because HTTPotion's spec for `get` doesn't include that possibility, either.

Unfortunately, it's possible to get a `nil` when the element doesn't exist on Zendesk:
```
iex(1)> ZenEx.Model.Ticket.show(-123)
nil
```

That also rings true for Locale and User:
```
iex(2)> ZenEx.Model.User.show(-123)
nil
iex(3)> ZenEx.Model.Locale.show(1231238129321381293912389)
nil
```

I can submit a quick PR that adds the `nil` return type for the specs and link it here if that works.

**Comment by otoyo** [comment]
Thank you for reporting the issue!
Please add nil to spec.

**Comment by onizuka8** [comment]
Hello, I think this issue is related on how api responses are handled. Response status is not validate and all the responses (even with error codes eg 400) are still calling [_build_entity](https://github.com/otoyo/zen_ex/blob/main/lib/zen_ex/http_client.ex#L61); which returns nil because it won't find the required key in the response body. Indeed, most of the modules seems to specify only {:error, String.t()} and not nil

I think the HTTPClient should be updated to handle error responses. For instance I would expect something like this:

```
iex(1)> ZenEx.Model.Ticket.show(-123)
{:error, "You passed an invalid value for the id attribute. Invalid parameter: id must be greater than or equal to 0 from api/v2/tickets/show"}

iex(1)> ZenEx.Model.Ticket.show(100000000)
{:error, "Not found}
```

Zendesk body for api/v2/tickets/show with 404:  
`body: "{\"error\":\"RecordNotFound\",\"description\":\"Not found\"}"`)

**Comment by esambo** [comment]
I believe that I noticed a similar problem with `ZenEx.Model.Ticket.update/1`:
https://github.com/otoyo/zen_ex/blob/482ec1aa70cbfb2108c2362fced6baac67c062d3/lib/zen_ex/core/models/ticket.ex#L63-L66
where it returns an unexpected `nil` in production, rather than an `{:error, reason}` that would help to troubleshoot the underlying ZenDesk response error.
I believe that this is because `ZenEx.HTTPClient.update/3`:
https://github.com/otoyo/zen_ex/blob/482ec1aa70cbfb2108c2362fced6baac67c062d3/lib/zen_ex/http_client.ex#L42-L45
and it's `ZenEx.HTTPClient._build_entity/2`:
https://github.com/otoyo/zen_ex/blob/482ec1aa70cbfb2108c2362fced6baac67c062d3/lib/zen_ex/http_client.ex#L76-L77
don't first validate that the response is of the expected shape and only assume the happy path scenario.

**I can recreate this behavior with**:
```elixir
Mix.install([
  {:poison, "~> 3.1"},
  {:tesla, "~> 1.4.4"},
  {:zen_ex, "~> 0.7.0"}
])

import ZenEx.HTTPClient, only: [_build_entity: 2]
alias Tesla.Env
alias ZenEx.Entity.Ticket

decode_as = [ticket: Ticket]
body = "{}"
response = %Env{body: body}
response |> _build_entity(decode_as)
# => nil
```
